### ISSUE TITLE
README files doesn't have compile and run instructions

### ISSUE THREAD

**Issue by robertsawko** [AlexSkillen/OpenFOAM_SEM#1]
I am going to have a look quickly if I can add them. Should be easy and make it useful for people who are not so familiar with user code compilation.

**Comment by AlexSkillen** [comment]
Thanks @robertsawko, that will be useful

**Comment by robertsawko** [comment]
Sent you a PR. Have a look. I actually deleted the U file as I think it's cleaner to have just a mention in the README, but this might be just taste.

**Comment by AlexSkillen** [comment]
Thank you Robert. Fixed in PR.
