### ISSUE TITLE
Velocity file contains is mesh specific and very large

### ISSUE THREAD

**Issue by robertsawko** [AlexSkillen/OpenFOAM_SEM#2]
I think a uniform Rin and Uin would be better for the sake of a repository and only mention the non-uniform one. Two problems I see here is that `U` is quite a large file so hard to read and modify and still slow to clone on wifis (especially if you're not doing this in contries with slower Internet!).

I feel that if you have a repository like this we need to make everything to make it more accessible. Hope that's an okay feedback.

**Comment by AlexSkillen** [comment]
Agreed. Let's change it to uniform values.

**Comment by AlexSkillen** [comment]
Addressed in 5b0d555dca48a9e78f49ce5bcfb3c555de4053bf
