### ISSUE TITLE
ReconstructPar fails in ofv1612+

### ISSUE THREAD

**Issue by Raul-Ciria-Aylagas** [AlexSkillen/OpenFOAM_SEM#5]
Hello,
I've compiled this BC in OFv1612+ . I just had to adapt the functions randomise01() and change them to randomise(). However, it fails on reconstructPar as the initilise function throws a floating point exception in the calculation of avgWindow_. I think that it is not a version specific error, but the problem is that all the processors evaluate the funcion initilise, and if they don't have eddies, then this fails. Have you found this error in 1806 too? Could you give me a hint on how to solve it?

**Comment by AlexSkillen** [comment]
I recall seeing this behaviour in the past. Not a fix, but a possible workaround for now might be to not load the library when using reconstructPar (comment it out in controlDict). Let me know if this helps.
I'm not actively working on this project at the moment, so have very little time to debug it, but if you do manage to fix it, please to submit a merge request. Thanks!

**Comment by Raul-Ciria-Aylagas** [comment]
Hello Alex, I managed to solve the problem. I have created a merge request with the solution.
Regards

**Comment by AlexSkillen** [comment]
Thanks!
